services:
  artemis:
    image: apache/activemq-artemis:latest
    volumes:
      - ./etc-override:/var/lib/artemis-instance/etc-override
    container_name: artemis
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
      - TZ=America/Argentina/Buenos_Aires  
    ports:
      - "61616:61616"  # Artemis core
#      - "1099:1099"    # JMX (si usas la configuración JVM)
      - "8161:8161"    # Web console
#      - "1098:1098"  
   
